// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyf1EJUVku2nkWPFBv7NVKmzP3lF0i5o',
    appId: '1:393875381074:web:a8cb95cbf98da94dd6788b',
    messagingSenderId: '393875381074',
    projectId: 'crud-5734e',
    authDomain: 'crud-5734e.firebaseapp.com',
    storageBucket: 'crud-5734e.appspot.com',
    measurementId: 'G-9D6FZ631C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInh6HF8L05crrmJxs32x8Ah-1EfsQJDI',
    appId: '1:393875381074:android:49d9dc093464a4a9d6788b',
    messagingSenderId: '393875381074',
    projectId: 'crud-5734e',
    storageBucket: 'crud-5734e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf8fsY33-Tiuzv9NiMarJxfYrdn01r-qA',
    appId: '1:393875381074:ios:eef3b796282053e8d6788b',
    messagingSenderId: '393875381074',
    projectId: 'crud-5734e',
    storageBucket: 'crud-5734e.appspot.com',
    iosBundleId: 'com.example.crudRef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf8fsY33-Tiuzv9NiMarJxfYrdn01r-qA',
    appId: '1:393875381074:ios:eef3b796282053e8d6788b',
    messagingSenderId: '393875381074',
    projectId: 'crud-5734e',
    storageBucket: 'crud-5734e.appspot.com',
    iosBundleId: 'com.example.crudRef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPyf1EJUVku2nkWPFBv7NVKmzP3lF0i5o',
    appId: '1:393875381074:web:3326a3cb72d937dad6788b',
    messagingSenderId: '393875381074',
    projectId: 'crud-5734e',
    authDomain: 'crud-5734e.firebaseapp.com',
    storageBucket: 'crud-5734e.appspot.com',
    measurementId: 'G-W6FM56D3FP',
  );
}
